CREATE TABLE covid CLONE "UDACITYNANODEGREE"."ODS".COVID ;

CREATE TABLE tip CLONE "UDACITYNANODEGREE"."ODS".TIP;

CREATE TABLE user CLONE "UDACITYNANODEGREE"."ODS".USER ;

CREATE TABLE review CLONE "UDACITYNANODEGREE"."ODS".REVIEW;

CREATE TABLE business CLONE "UDACITYNANODEGREE"."ODS".BUSINESS ;

CREATE TABLE checkin CLONE "UDACITYNANODEGREE"."ODS".CHECKIN ;

CREATE TABLE precipitation CLONE "UDACITYNANODEGREE"."ODS".PRECIPITATION;

CREATE TABLE temperature CLONE "UDACITYNANODEGREE"."ODS".TEMPERATURE;

CREATE TABLE total_info CLONE "UDACITYNANODEGREE"."ODS".total_info;
